[versions]
agp = "9.0.1"
androidx-junit = "1.3.0"
androidx-localbroadcast = "1.1.0"
androidx-rules = "1.7.0"
androidx-runner = "1.7.0"
appcompat = "1.7.1"
commons-io = "2.21.0"
commons-net = "3.12.0"
dokka = "2.1.0"
jtorctl = "0.4.5.7"
kotlin = "2.3.10"
netcipher = "2.1.0"
nmcp = "1.4.4"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-localbroadcast = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "androidx-localbroadcast" }
androidx-rules = { module = "androidx.test:rules", version.ref = "androidx-rules" }
androidx-runner = { module = "androidx.test:runner", version.ref = "androidx-runner" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-net = { module = "commons-net:commons-net", version.ref = "commons-net" }
jtorctl = { module = "info.guardianproject:jtorctl", version.ref = "jtorctl" }
netcipher = { module = "info.guardianproject.netcipher:netcipher", version.ref = "netcipher" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
nmcp-aggregation = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }
android-application = { id = "com.android.application", version.ref = "agp" }

